// Code generated by go-swagger; DO NOT EDIT.

package users

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	models "github.com/Easprey/whiteboard-server/models"
)

// BoardsFingerpathsByBoardNameGetOKCode is the HTTP code returned for type BoardsFingerpathsByBoardNameGetOK
const BoardsFingerpathsByBoardNameGetOKCode int = 200

/*BoardsFingerpathsByBoardNameGetOK fingerpaths associated with board

swagger:response boardsFingerpathsByBoardNameGetOK
*/
type BoardsFingerpathsByBoardNameGetOK struct {

	/*
	  In: Body
	*/
	Payload []*models.FingerPath `json:"body,omitempty"`
}

// NewBoardsFingerpathsByBoardNameGetOK creates BoardsFingerpathsByBoardNameGetOK with default headers values
func NewBoardsFingerpathsByBoardNameGetOK() *BoardsFingerpathsByBoardNameGetOK {

	return &BoardsFingerpathsByBoardNameGetOK{}
}

// WithPayload adds the payload to the boards fingerpaths by board name get o k response
func (o *BoardsFingerpathsByBoardNameGetOK) WithPayload(payload []*models.FingerPath) *BoardsFingerpathsByBoardNameGetOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the boards fingerpaths by board name get o k response
func (o *BoardsFingerpathsByBoardNameGetOK) SetPayload(payload []*models.FingerPath) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *BoardsFingerpathsByBoardNameGetOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	payload := o.Payload
	if payload == nil {
		// return empty array
		payload = make([]*models.FingerPath, 0, 50)
	}

	if err := producer.Produce(rw, payload); err != nil {
		panic(err) // let the recovery middleware deal with this
	}
}

// BoardsFingerpathsByBoardNameGetBadRequestCode is the HTTP code returned for type BoardsFingerpathsByBoardNameGetBadRequest
const BoardsFingerpathsByBoardNameGetBadRequestCode int = 400

/*BoardsFingerpathsByBoardNameGetBadRequest no associated board

swagger:response boardsFingerpathsByBoardNameGetBadRequest
*/
type BoardsFingerpathsByBoardNameGetBadRequest struct {

	/*
	  In: Body
	*/
	Payload interface{} `json:"body,omitempty"`
}

// NewBoardsFingerpathsByBoardNameGetBadRequest creates BoardsFingerpathsByBoardNameGetBadRequest with default headers values
func NewBoardsFingerpathsByBoardNameGetBadRequest() *BoardsFingerpathsByBoardNameGetBadRequest {

	return &BoardsFingerpathsByBoardNameGetBadRequest{}
}

// WithPayload adds the payload to the boards fingerpaths by board name get bad request response
func (o *BoardsFingerpathsByBoardNameGetBadRequest) WithPayload(payload interface{}) *BoardsFingerpathsByBoardNameGetBadRequest {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the boards fingerpaths by board name get bad request response
func (o *BoardsFingerpathsByBoardNameGetBadRequest) SetPayload(payload interface{}) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *BoardsFingerpathsByBoardNameGetBadRequest) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(400)
	payload := o.Payload
	if err := producer.Produce(rw, payload); err != nil {
		panic(err) // let the recovery middleware deal with this
	}
}
