// Code generated by go-swagger; DO NOT EDIT.

package users

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"
)

// BoardsFingerpathsByBoardNamePostCreatedCode is the HTTP code returned for type BoardsFingerpathsByBoardNamePostCreated
const BoardsFingerpathsByBoardNamePostCreatedCode int = 201

/*BoardsFingerpathsByBoardNamePostCreated fingerpaths added

swagger:response boardsFingerpathsByBoardNamePostCreated
*/
type BoardsFingerpathsByBoardNamePostCreated struct {
}

// NewBoardsFingerpathsByBoardNamePostCreated creates BoardsFingerpathsByBoardNamePostCreated with default headers values
func NewBoardsFingerpathsByBoardNamePostCreated() *BoardsFingerpathsByBoardNamePostCreated {

	return &BoardsFingerpathsByBoardNamePostCreated{}
}

// WriteResponse to the client
func (o *BoardsFingerpathsByBoardNamePostCreated) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(201)
}

// BoardsFingerpathsByBoardNamePostBadRequestCode is the HTTP code returned for type BoardsFingerpathsByBoardNamePostBadRequest
const BoardsFingerpathsByBoardNamePostBadRequestCode int = 400

/*BoardsFingerpathsByBoardNamePostBadRequest no associate board

swagger:response boardsFingerpathsByBoardNamePostBadRequest
*/
type BoardsFingerpathsByBoardNamePostBadRequest struct {

	/*
	  In: Body
	*/
	Payload interface{} `json:"body,omitempty"`
}

// NewBoardsFingerpathsByBoardNamePostBadRequest creates BoardsFingerpathsByBoardNamePostBadRequest with default headers values
func NewBoardsFingerpathsByBoardNamePostBadRequest() *BoardsFingerpathsByBoardNamePostBadRequest {

	return &BoardsFingerpathsByBoardNamePostBadRequest{}
}

// WithPayload adds the payload to the boards fingerpaths by board name post bad request response
func (o *BoardsFingerpathsByBoardNamePostBadRequest) WithPayload(payload interface{}) *BoardsFingerpathsByBoardNamePostBadRequest {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the boards fingerpaths by board name post bad request response
func (o *BoardsFingerpathsByBoardNamePostBadRequest) SetPayload(payload interface{}) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *BoardsFingerpathsByBoardNamePostBadRequest) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(400)
	payload := o.Payload
	if err := producer.Produce(rw, payload); err != nil {
		panic(err) // let the recovery middleware deal with this
	}
}
