// Code generated by go-swagger; DO NOT EDIT.

package users

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"
)

// PostBoardsBoardNameFingerpathsCreatedCode is the HTTP code returned for type PostBoardsBoardNameFingerpathsCreated
const PostBoardsBoardNameFingerpathsCreatedCode int = 201

/*PostBoardsBoardNameFingerpathsCreated fingerpaths added

swagger:response postBoardsBoardNameFingerpathsCreated
*/
type PostBoardsBoardNameFingerpathsCreated struct {
}

// NewPostBoardsBoardNameFingerpathsCreated creates PostBoardsBoardNameFingerpathsCreated with default headers values
func NewPostBoardsBoardNameFingerpathsCreated() *PostBoardsBoardNameFingerpathsCreated {

	return &PostBoardsBoardNameFingerpathsCreated{}
}

// WriteResponse to the client
func (o *PostBoardsBoardNameFingerpathsCreated) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(201)
}

// PostBoardsBoardNameFingerpathsBadRequestCode is the HTTP code returned for type PostBoardsBoardNameFingerpathsBadRequest
const PostBoardsBoardNameFingerpathsBadRequestCode int = 400

/*PostBoardsBoardNameFingerpathsBadRequest no associate board

swagger:response postBoardsBoardNameFingerpathsBadRequest
*/
type PostBoardsBoardNameFingerpathsBadRequest struct {

	/*
	  In: Body
	*/
	Payload interface{} `json:"body,omitempty"`
}

// NewPostBoardsBoardNameFingerpathsBadRequest creates PostBoardsBoardNameFingerpathsBadRequest with default headers values
func NewPostBoardsBoardNameFingerpathsBadRequest() *PostBoardsBoardNameFingerpathsBadRequest {

	return &PostBoardsBoardNameFingerpathsBadRequest{}
}

// WithPayload adds the payload to the post boards board name fingerpaths bad request response
func (o *PostBoardsBoardNameFingerpathsBadRequest) WithPayload(payload interface{}) *PostBoardsBoardNameFingerpathsBadRequest {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the post boards board name fingerpaths bad request response
func (o *PostBoardsBoardNameFingerpathsBadRequest) SetPayload(payload interface{}) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *PostBoardsBoardNameFingerpathsBadRequest) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(400)
	payload := o.Payload
	if err := producer.Produce(rw, payload); err != nil {
		panic(err) // let the recovery middleware deal with this
	}
}
