// Code generated by go-swagger; DO NOT EDIT.

package fingerpaths

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	middleware "github.com/go-openapi/runtime/middleware"
)

// GetFingerPathsByBoardHandlerFunc turns a function with the right signature into a get finger paths by board handler
type GetFingerPathsByBoardHandlerFunc func(GetFingerPathsByBoardParams) middleware.Responder

// Handle executing the request and returning a response
func (fn GetFingerPathsByBoardHandlerFunc) Handle(params GetFingerPathsByBoardParams) middleware.Responder {
	return fn(params)
}

// GetFingerPathsByBoardHandler interface for that can handle valid get finger paths by board params
type GetFingerPathsByBoardHandler interface {
	Handle(GetFingerPathsByBoardParams) middleware.Responder
}

// NewGetFingerPathsByBoard creates a new http.Handler for the get finger paths by board operation
func NewGetFingerPathsByBoard(ctx *middleware.Context, handler GetFingerPathsByBoardHandler) *GetFingerPathsByBoard {
	return &GetFingerPathsByBoard{Context: ctx, Handler: handler}
}

/*GetFingerPathsByBoard swagger:route GET /boards/{boardName}/fingerpaths fingerpaths getFingerPathsByBoard

Gets all fingerpaths associated with the given board.


*/
type GetFingerPathsByBoard struct {
	Context *middleware.Context
	Handler GetFingerPathsByBoardHandler
}

func (o *GetFingerPathsByBoard) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		r = rCtx
	}
	var Params = NewGetFingerPathsByBoardParams()

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params) // actually handle the request

	o.Context.Respond(rw, r, route.Produces, route, res)

}
