// Code generated by go-swagger; DO NOT EDIT.

package fingerpaths

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	middleware "github.com/go-openapi/runtime/middleware"
)

// PostFingerPathsByBoardHandlerFunc turns a function with the right signature into a post finger paths by board handler
type PostFingerPathsByBoardHandlerFunc func(PostFingerPathsByBoardParams) middleware.Responder

// Handle executing the request and returning a response
func (fn PostFingerPathsByBoardHandlerFunc) Handle(params PostFingerPathsByBoardParams) middleware.Responder {
	return fn(params)
}

// PostFingerPathsByBoardHandler interface for that can handle valid post finger paths by board params
type PostFingerPathsByBoardHandler interface {
	Handle(PostFingerPathsByBoardParams) middleware.Responder
}

// NewPostFingerPathsByBoard creates a new http.Handler for the post finger paths by board operation
func NewPostFingerPathsByBoard(ctx *middleware.Context, handler PostFingerPathsByBoardHandler) *PostFingerPathsByBoard {
	return &PostFingerPathsByBoard{Context: ctx, Handler: handler}
}

/*PostFingerPathsByBoard swagger:route POST /boards/{boardName}/fingerpaths fingerpaths postFingerPathsByBoard

Adds fingerpaths to the associated board.

*/
type PostFingerPathsByBoard struct {
	Context *middleware.Context
	Handler PostFingerPathsByBoardHandler
}

func (o *PostFingerPathsByBoard) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		r = rCtx
	}
	var Params = NewPostFingerPathsByBoardParams()

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params) // actually handle the request

	o.Context.Respond(rw, r, route.Produces, route, res)

}
