// Code generated by go-swagger; DO NOT EDIT.

package fingerpaths

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	"github.com/go-openapi/runtime/middleware"

	strfmt "github.com/go-openapi/strfmt"

	models "github.com/Easprey/whiteboard-server/models"
)

// NewPostFingerPathsByBoardParams creates a new PostFingerPathsByBoardParams object
// no default values defined in spec.
func NewPostFingerPathsByBoardParams() PostFingerPathsByBoardParams {

	return PostFingerPathsByBoardParams{}
}

// PostFingerPathsByBoardParams contains all the bound params for the post finger paths by board operation
// typically these are obtained from a http.Request
//
// swagger:parameters postFingerPathsByBoard
type PostFingerPathsByBoardParams struct {

	// HTTP Request Object
	HTTPRequest *http.Request `json:"-"`

	/*the name of the board
	  Required: true
	  In: path
	*/
	BoardName string
	/*Inventory item to add
	  In: body
	*/
	Body []*models.FingerPath
}

// BindRequest both binds and validates a request, it assumes that complex things implement a Validatable(strfmt.Registry) error interface
// for simple values it will use straight method calls.
//
// To ensure default values, the struct must have been initialized with NewPostFingerPathsByBoardParams() beforehand.
func (o *PostFingerPathsByBoardParams) BindRequest(r *http.Request, route *middleware.MatchedRoute) error {
	var res []error

	o.HTTPRequest = r

	rBoardName, rhkBoardName, _ := route.Params.GetOK("boardName")
	if err := o.bindBoardName(rBoardName, rhkBoardName, route.Formats); err != nil {
		res = append(res, err)
	}

	if runtime.HasBody(r) {
		defer r.Body.Close()
		var body []*models.FingerPath
		if err := route.Consumer.Consume(r.Body, &body); err != nil {
			res = append(res, errors.NewParseError("body", "body", "", err))
		} else {
			// validate array of body objects
			for i := range body {
				if body[i] == nil {
					continue
				}
				if err := body[i].Validate(route.Formats); err != nil {
					res = append(res, err)
					break
				}
			}
			if len(res) == 0 {
				o.Body = body
			}
		}
	}
	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

// bindBoardName binds and validates parameter BoardName from path.
func (o *PostFingerPathsByBoardParams) bindBoardName(rawData []string, hasKey bool, formats strfmt.Registry) error {
	var raw string
	if len(rawData) > 0 {
		raw = rawData[len(rawData)-1]
	}

	// Required: true
	// Parameter is provided by construction from the route

	o.BoardName = raw

	return nil
}
