// Code generated by go-swagger; DO NOT EDIT.

/*
Package restapi WhiteBoard API
API for the WhiteBoard app developed by Weberster Inc


    Schemes:
      http
    Host: localhost
    BasePath: /api/v1
    Version: 0.1.0
    Contact: <webersterinc@gmail.com>

    Consumes:
    - application/json

    Produces:
    - application/json

swagger:meta
*/
package restapi
