/*
 * WhiteBoard API
 *
 * API for the WhiteBoard app developed by Weberster Inc
 *
 * API version: 0.1.0
 * Contact: webersterinc@gmail.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

import (
	"net/http"
)

func BoardsFingerpathsByBoardNameGet(w http.ResponseWriter, r *http.Request) {
	w.Header().Set("Content-Type", "application/json; charset=UTF-8")
	w.WriteHeader(http.StatusOK)
}

func BoardsFingerpathsByBoardNamePost(w http.ResponseWriter, r *http.Request) {
	w.Header().Set("Content-Type", "application/json; charset=UTF-8")
	w.WriteHeader(http.StatusOK)
}
