/*
 * WhiteBoard API
 *
 * API for the WhiteBoard app developed by Weberster Inc
 *
 * API version: 0.1.0
 * Contact: webersterinc@gmail.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

type FingerPath struct {

	PathId int32 `json:"pathId,omitempty"`

	PathColor int32 `json:"pathColor"`

	Dash bool `json:"dash"`

	Blur bool `json:"blur"`

	Clear bool `json:"clear"`
}
