/*
 * WhiteBoard API
 *
 * API for the WhiteBoard app developed by Weberster Inc
 *
 * API version: 0.1.0
 * Contact: webersterinc@gmail.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

import (
	"fmt"
	"net/http"
	"strings"

	"github.com/gorilla/mux"
)

type Route struct {
	Name        string
	Method      string
	Pattern     string
	HandlerFunc http.HandlerFunc
}

type Routes []Route

func NewRouter() *mux.Router {
	router := mux.NewRouter().StrictSlash(true)
	for _, route := range routes {
		var handler http.Handler
		handler = route.HandlerFunc
		handler = Logger(handler, route.Name)

		router.
			Methods(route.Method).
			Path(route.Pattern).
			Name(route.Name).
			Handler(handler)
	}

	return router
}

func Index(w http.ResponseWriter, r *http.Request) {
	fmt.Fprintf(w, "Hello World!")
}

var routes = Routes{
	Route{
		"Index",
		"GET",
		"/WebersterInc/WhiteBoard/0.1.0/",
		Index,
	},

	Route{
		"BoardsFingerpathsByBoardNameGet",
		strings.ToUpper("Get"),
		"/WebersterInc/WhiteBoard/0.1.0/boards/{boardName}/fingerpaths",
		BoardsFingerpathsByBoardNameGet,
	},

	Route{
		"BoardsFingerpathsByBoardNamePost",
		strings.ToUpper("Post"),
		"/WebersterInc/WhiteBoard/0.1.0/boards/{boardName}/fingerpaths",
		BoardsFingerpathsByBoardNamePost,
	},
}
